// @ts-check
// 侧边导航
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  frontendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'front-end',
    },
  ],
  backendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'back-end',
    },
  ],
  c7nSidebar: [
    {
      type: 'autogenerated',
      dirName: 'c7n',
    },
  ],
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorial',
    },
  ],
  otherSidebar: [
    {
      type: 'autogenerated',
      dirName: 'other',
    },
  ],
};

module.exports = sidebars;
