import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// 侧边导航
const sidebars: SidebarsConfig = {
  frontendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'front-end',
    },
  ],
  backendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'back-end',
    },
  ],
  c7nSidebar: [
    {
      type: 'autogenerated',
      dirName: 'c7n',
    },
  ],
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorial',
    },
  ],
  otherSidebar: [
    {
      type: 'autogenerated',
      dirName: 'other',
    },
  ],
};

export default sidebars;
