// @ts-check
// 侧边导航
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  frontendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'FrontEnd'
    }
  ],
  c7nSidebar: [
    {
      type: 'autogenerated',
      dirName: 'C7N'
    }
  ],
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Tutorial'
    }
  ],
  otherSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Other'
    }
  ]
};

module.exports = sidebars;
